name:                riscv-rv32i
version:             0.1.0.0
github:              "mikiyaf/riscv-rv32i"
license:             BSD3
author:              "Mikiya Michishita"
maintainer:          "example@example.com"
copyright:           "2020 Mikiya Michishita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mikiyaf/riscv-rv32i#readme>

dependencies:
- base >= 4.7 && < 5
- ghc-typelits-natnormalise
- ghc-typelits-extra
- ghc-typelits-knownnat
- clash-prelude
- deepseq
- hspec
- HUnit
- QuickCheck >= 2.14.2
- pretty-simple

default-extensions:
- DataKinds
- DeriveGeneric
- DeriveAnyClass
- KindSignatures
- FlexibleContexts
- RankNTypes
- QuantifiedConstraints
- ScopedTypeVariables
- MonoLocalBinds
- MagicHash
- TypeOperators
- TypeFamilies

library:
  source-dirs: src

executables:
  riscv-rv32i-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - riscv-rv32i

tests:
  riscv-rv32i-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - riscv-rv32i
